//! Raw FFI bindings to llama.cpp.
//!
//! Generated by `build.rs` via `bindgen` against the vendored header
//! at `vendor/llama.cpp/include/llama.h`, pinned to a specific SHA.
//!
//! # Safety
//!
//! Every symbol here is `unsafe`. Nothing in this module is allowed to
//! leave the crate boundary. All user-facing code goes through the safe
//! wrappers in [`crate::model`] and [`crate::context`].

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
