//! Metrics layer: `metrics` facade + Prometheus backend.
//!
//! Call sites record metrics through `metrics::counter!` / `gauge!` /
//! `histogram!` without naming a backend. At startup the node installs
//! a `metrics_exporter_prometheus` recorder; the recorder drains
//! periodically into the `/metrics` HTTP endpoint.
//!
//! Why the facade and not `prometheus` directly: you approved D5 with
//! the rationale that migrating later costs roughly 2× what it costs
//! now. The runtime overhead over a direct `prometheus` counter is
//! ~one atomic store — negligible for anything we'll record.
//!
//! Metric naming convention: `arknet_<subsystem>_<noun>_<unit>` in
//! Prometheus-snake-case (note: the `metrics` crate accepts both
//! `arknet_subsystem_noun` and `arknet.subsystem.noun`; the Prometheus
//! exporter normalizes dots to underscores).

#![allow(dead_code)]

use std::net::SocketAddr;
use std::sync::Arc;

use metrics_exporter_prometheus::{PrometheusBuilder, PrometheusHandle};
use parking_lot::Mutex;
use tokio::net::TcpListener;
use tokio_util::sync::CancellationToken;
use tracing::{info, warn};

use crate::errors::{NodeError, Result};

/// Shared metrics handle kept alive for the process lifetime.
///
/// Installing the recorder is a one-shot operation. If called twice
/// (e.g. from tests that spin up multiple runtimes in the same
/// process) the second call is a no-op and returns the original
/// handle. The `Mutex<Option<PrometheusHandle>>` guards against the
/// race between two concurrent installers.
#[derive(Clone)]
pub struct MetricsRegistry {
    handle: Arc<PrometheusHandle>,
}

static INSTALLED: Mutex<Option<Arc<PrometheusHandle>>> = Mutex::new(None);

impl MetricsRegistry {
    /// Install the Prometheus recorder if it isn't already installed.
    /// Idempotent across calls (safe in tests).
    pub fn install() -> Result<Self> {
        let mut guard = INSTALLED.lock();
        if let Some(handle) = guard.as_ref() {
            return Ok(Self {
                handle: handle.clone(),
            });
        }

        let recorder = PrometheusBuilder::new().build_recorder();
        let handle = recorder.handle();
        metrics::set_global_recorder(recorder)
            .map_err(|e| NodeError::Config(format!("global recorder already set: {e}")))?;

        let owned = Arc::new(handle);
        *guard = Some(owned.clone());
        register_common_metrics();

        Ok(Self { handle: owned })
    }

    /// Render the current metrics in Prometheus text format.
    pub fn render(&self) -> String {
        self.handle.render()
    }
}

/// Declare the small set of process-wide metrics we expose from day 1.
/// Per-subsystem crates register their own via the same macros at
/// call sites; this just seeds the ones the runtime scaffold owns.
fn register_common_metrics() {
    metrics::describe_counter!(
        "arknet_node_starts_total",
        "Number of times the node has booted since this recorder was installed."
    );
    metrics::describe_gauge!(
        "arknet_node_uptime_seconds",
        "Seconds since the node most recently booted."
    );
    metrics::describe_counter!(
        "arknet_inference_tokens_generated_total",
        "Total output tokens generated by the inference engine across all sessions."
    );
    metrics::describe_counter!(
        "arknet_inference_sessions_total",
        "Total inference sessions started, labeled by terminal reason."
    );
    metrics::describe_histogram!(
        "arknet_inference_session_seconds",
        "Wall-clock duration of an inference session from start to stop event."
    );

    // Phase-1 Week 12 additions.
    metrics::describe_gauge!("arknet_consensus_height", "Latest finalized block height.");
    metrics::describe_gauge!(
        "arknet_consensus_round",
        "Current consensus round within the active height."
    );
    metrics::describe_gauge!(
        "arknet_consensus_validator_set_size",
        "Number of active validators in the current epoch."
    );
    metrics::describe_gauge!(
        "arknet_mempool_depth",
        "Number of pending transactions in the mempool."
    );
    metrics::describe_gauge!(
        "arknet_mempool_bytes",
        "Total encoded bytes of pending transactions."
    );
    metrics::describe_counter!(
        "arknet_receipts_anchored_total",
        "Cumulative count of receipts anchored onto L1."
    );
    metrics::describe_counter!(
        "arknet_disputes_filed_total",
        "Cumulative count of Dispute transactions accepted by the chain."
    );
    metrics::describe_counter!(
        "arknet_inference_jobs_total",
        "Total inference jobs dispatched by the router."
    );

    // Stake these as zero so /metrics returns something even before the
    // first event fires.
    metrics::counter!("arknet_node_starts_total").increment(1);
}

/// Run a Prometheus `/metrics` HTTP endpoint until `shutdown` fires.
///
/// Intentionally tiny — no router, no middleware, no state other than
/// the registry handle. This is the minimum viable scrape endpoint.
pub async fn serve(
    bind: SocketAddr,
    registry: MetricsRegistry,
    shutdown: CancellationToken,
) -> Result<()> {
    let listener = TcpListener::bind(bind).await?;
    let addr = listener.local_addr()?;
    info!(%addr, "metrics: /metrics endpoint bound");

    let app = axum::Router::new()
        .route("/metrics", axum::routing::get(metrics_handler))
        .with_state(registry);

    let server = axum::serve(listener, app).with_graceful_shutdown(async move {
        shutdown.cancelled().await;
    });

    if let Err(e) = server.await {
        warn!(error = %e, "metrics server exited with error");
        return Err(NodeError::Config(format!("metrics server: {e}")));
    }
    info!("metrics: server stopped cleanly");
    Ok(())
}

async fn metrics_handler(
    axum::extract::State(registry): axum::extract::State<MetricsRegistry>,
) -> impl axum::response::IntoResponse {
    (
        [(
            axum::http::header::CONTENT_TYPE,
            "text/plain; version=0.0.4",
        )],
        registry.render(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    // `install` is process-global, so multiple tests share one recorder.
    // All tests here merely exercise the render path and the HTTP
    // handler — they must tolerate other tests already having bumped
    // counters. The `install` call itself is idempotent.

    #[test]
    fn install_is_idempotent() {
        let a = MetricsRegistry::install().unwrap();
        let b = MetricsRegistry::install().unwrap();
        // Both should render successfully.
        let out_a = a.render();
        let out_b = b.render();
        assert!(
            out_a.contains("arknet_node_starts_total")
                || out_b.contains("arknet_node_starts_total")
        );
    }

    #[tokio::test]
    async fn metrics_endpoint_serves_recorder_output() {
        let registry = MetricsRegistry::install().unwrap();
        let shutdown = CancellationToken::new();

        // Bind to an OS-assigned port.
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        drop(listener);

        let shutdown_for_server = shutdown.clone();
        let server_registry = registry.clone();
        let server =
            tokio::spawn(async move { serve(addr, server_registry, shutdown_for_server).await });

        // Small retry loop — the server may not be bound the instant we poll.
        let client = reqwest::Client::new();
        let mut body = None;
        for _ in 0..20 {
            tokio::time::sleep(std::time::Duration::from_millis(25)).await;
            if let Ok(resp) = client.get(format!("http://{addr}/metrics")).send().await {
                if resp.status().is_success() {
                    body = Some(resp.text().await.unwrap());
                    break;
                }
            }
        }

        shutdown.cancel();
        let _ = server.await;

        let body = body.expect("/metrics did not respond");
        assert!(body.contains("arknet_node_starts_total"));
    }
}
