//! Data-directory resolution.
//!
//! Several helpers here are consumed across Days 2-10 (init, config,
//! start, model commands). Until those land, suppress dead-code
//! warnings so `clippy -D warnings` stays green on the Day 1 scaffold.
//!
//! Precedence: `--data-dir <path>` flag > `ARKNET_HOME` env > `~/.arknet/`.
//!
//! We use `~/.arknet/` on all three supported platforms. Non-idiomatic
//! on Windows (where `%LOCALAPPDATA%\arknet\` would be the Apple-HIG /
//! Microsoft convention) but widely precedented in the infra / crypto
//! space — Docker, Helm, Geth, Bitcoin Core all use dotdirs. One
//! convention across platforms is the simpler operator story.
//!
//! The directory layout:
//!
//! ```text
//! <data-dir>/
//! ├── node.toml             ← generated by `arknet init`
//! ├── models/               ← content-addressed model cache
//! ├── keys/                 ← operator key material
//! └── logs/                 ← tracing output when file logging enabled
//! ```

#![allow(dead_code)]

use std::path::{Path, PathBuf};

use crate::errors::{NodeError, Result};

/// Environment variable that overrides the default data directory.
pub const ENV_DATA_DIR: &str = "ARKNET_HOME";

/// Resolve the effective data directory.
///
/// `cli_override` takes precedence, then `ARKNET_HOME`, then the
/// default (`~/.arknet/`). Does NOT create the directory; callers use
/// [`ensure_layout`] for that.
pub fn resolve(cli_override: Option<&Path>) -> Result<PathBuf> {
    if let Some(p) = cli_override {
        return Ok(p.to_path_buf());
    }
    if let Ok(env) = std::env::var(ENV_DATA_DIR) {
        if !env.is_empty() {
            return Ok(PathBuf::from(env));
        }
    }
    default_data_dir()
}

/// The system default, `~/.arknet/`. Fails if we can't determine a home
/// directory (rare — only on deeply broken environments).
pub fn default_data_dir() -> Result<PathBuf> {
    let home = dirs::home_dir()
        .ok_or_else(|| NodeError::Paths("could not determine home directory".into()))?;
    Ok(home.join(".arknet"))
}

/// Subdirectory for the content-addressed model cache.
pub fn models_dir(root: &Path) -> PathBuf {
    root.join("models")
}

/// Subdirectory for operator key material.
pub fn keys_dir(root: &Path) -> PathBuf {
    root.join("keys")
}

/// Subdirectory for tracing log files.
pub fn logs_dir(root: &Path) -> PathBuf {
    root.join("logs")
}

/// Path to the node config file.
pub fn node_toml(root: &Path) -> PathBuf {
    root.join("node.toml")
}

/// L1 chain state directory (RocksDB column families live here).
pub fn l1_dir(root: &Path) -> PathBuf {
    root.join("l1")
}

/// Path to the genesis file. Looked up first at `<data-dir>/genesis.toml`
/// (operator-placed); validators bail at boot if missing.
pub fn genesis_toml(root: &Path) -> PathBuf {
    root.join("genesis.toml")
}

/// Create the standard directory layout if any piece is missing.
/// Idempotent.
pub fn ensure_layout(root: &Path) -> Result<()> {
    for dir in [
        root.to_path_buf(),
        models_dir(root),
        keys_dir(root),
        logs_dir(root),
        l1_dir(root),
    ] {
        std::fs::create_dir_all(&dir)
            .map_err(|e| NodeError::Paths(format!("failed to create {}: {}", dir.display(), e)))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cli_override_wins() {
        let tmp = tempfile::tempdir().unwrap();
        let resolved = resolve(Some(tmp.path())).unwrap();
        assert_eq!(resolved, tmp.path());
    }

    #[test]
    fn env_var_used_when_no_override() {
        // Guarded by a temp home so the test doesn't pollute.
        let tmp = tempfile::tempdir().unwrap();
        let guard = EnvGuard::set(ENV_DATA_DIR, tmp.path().to_str().unwrap());
        let resolved = resolve(None).unwrap();
        assert_eq!(resolved, tmp.path());
        drop(guard);
    }

    #[test]
    fn ensure_layout_is_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        ensure_layout(tmp.path()).unwrap();
        ensure_layout(tmp.path()).unwrap();
        assert!(models_dir(tmp.path()).exists());
        assert!(keys_dir(tmp.path()).exists());
        assert!(logs_dir(tmp.path()).exists());
        assert!(l1_dir(tmp.path()).exists());
    }

    // Scoped env-var setter for tests.
    struct EnvGuard {
        key: &'static str,
        prev: Option<String>,
    }
    impl EnvGuard {
        fn set(key: &'static str, value: &str) -> Self {
            let prev = std::env::var(key).ok();
            // SAFETY: tests are single-threaded by default when using env.
            // `cargo test` serializes env-mutating tests if needed via
            // explicit `#[serial]`, which we don't require here because
            // only this test reads the var.
            unsafe {
                std::env::set_var(key, value);
            }
            Self { key, prev }
        }
    }
    impl Drop for EnvGuard {
        fn drop(&mut self) {
            unsafe {
                match &self.prev {
                    Some(v) => std::env::set_var(self.key, v),
                    None => std::env::remove_var(self.key),
                }
            }
        }
    }
}
