//! `arknet init` — create the data directory + default `node.toml`.
//!
//! Idempotent by default: if `node.toml` exists, errors out unless
//! `--force` is passed. The other subdirectories (`models/`, `keys/`,
//! `logs/`) are always ensured — creating missing ones never hurts.
//!
//! The generated TOML is commented up front so operators can land in
//! the file and understand each section without opening the docs.

use std::path::Path;

use clap::Args;

use crate::errors::{NodeError, Result};
use crate::paths;

#[derive(Args, Debug)]
pub struct InitArgs {
    /// Overwrite an existing node.toml if present.
    #[arg(long)]
    pub force: bool,
}

pub async fn run(args: InitArgs, data_dir: Option<&Path>) -> Result<()> {
    let root = paths::resolve(data_dir)?;
    paths::ensure_layout(&root)?;

    let toml_path = paths::node_toml(&root);
    if toml_path.exists() && !args.force {
        return Err(NodeError::Config(format!(
            "node.toml already exists at {}; pass --force to overwrite",
            toml_path.display()
        )));
    }

    let body = render_default_toml(&root);
    std::fs::write(&toml_path, body)?;

    println!("arknet init: data directory ready at {}", root.display());
    println!("  config:  {}", toml_path.display());
    println!("  models:  {}", paths::models_dir(&root).display());
    println!("  keys:    {}", paths::keys_dir(&root).display());
    println!("  logs:    {}", paths::logs_dir(&root).display());
    println!();
    println!("Edit node.toml, then: arknet start --role compute");
    Ok(())
}

/// Render a well-commented default `node.toml` under the given data dir.
///
/// Kept as a hand-written template (not `toml::to_string`) so the
/// comments survive — serde doesn't emit them. The values mirror the
/// defaults in `arknet_common::config::NodeConfig` except for
/// `data_dir`, which we write as the actual resolved path.
fn render_default_toml(data_dir: &Path) -> String {
    // Escape the path for TOML. On Windows paths contain backslashes
    // that the TOML spec requires escaping in basic strings; using a
    // literal string ('...') sidesteps that.
    let data_dir_literal = data_dir.display().to_string();

    format!(
        r#"# arknet node configuration
#
# Generated by `arknet init`. Edit in place and restart the node.
# Every field below is optional — omit anything you want to leave at
# the workspace default. Unknown fields are rejected to catch typos.
#
# See docs/NODE_OPERATOR_GUIDE.md for a full reference.

# ─── Identity ──────────────────────────────────────────────────────────
[node]
# Human-readable name shown in logs and the block explorer.
name = "arknet-node"
# Network to connect to: `devnet` | `testnet` | `mainnet`.
network = "devnet"
# Data directory: model cache, state DB, logs. Change with care —
# `arknet init` wrote the one below based on --data-dir / ARKNET_HOME.
data_dir = '{data_dir}'
# Log filter. Accepts the same syntax as `RUST_LOG`
# (e.g. "debug,llama=warn"). Env var RUST_LOG overrides this.
log_level = "info,llama=warn"

# ─── Roles ─────────────────────────────────────────────────────────────
# Turn at least one role on before `arknet start`. Phase 0 only runs
# `compute`; the others are planned for Phase 1+.
[roles]
validator = false  # L1 consensus (Phase 1+)
router    = false  # L2 request orchestration (Phase 1+)
compute   = true   # L2 inference (Phase 0)
verifier  = false  # L2 output verification (Phase 1+)

# ─── Resource budgets ──────────────────────────────────────────────────
# Per-role hardware caps. Empty vectors / zero values mean "no limit"
# or "use the engine default". Override only what you need.
[resources.compute]
# GPU indices to expose to the inference engine. Empty = CPU only.
# The deterministic verifier path always ignores GPUs.
gpu_devices           = []
# Cap across all loaded models in GiB; 0 = engine default.
max_vram_gb           = 0
# Max concurrent inference sessions on this node.
max_concurrent_jobs   = 1
# Models to pre-load at startup. Format: "<org>/<name>-<QUANT>".
# Example: loaded_models = ["test-org/Stories260K-F32"]
loaded_models         = []
# Allow the scheduler to evict loaded models on higher demand.
model_swap_enabled    = false

[resources.router]
cpu_percent           = 0   # 0 = no cap
max_concurrent_routes = 0
bandwidth_mbps        = 0

[resources.verifier]
gpu_share_with_compute     = false
max_verifications_per_hour = 0

[resources.validator]
# gossip_peers_max = 60
# remote_signer = "tcp://tmkms.local:23456"

# ─── Operator preferences ──────────────────────────────────────────────
[operator]
# payout_address       = "ark1..."        # mainnet: your reward address
# preferred_region     = "us-east"
# min_reward_per_job   = "0.0001"
auto_model_pull      = false
auto_pool_rebalance  = false

# ─── Networking ────────────────────────────────────────────────────────
[network]
# P2P libp2p listen address (Phase 1).
p2p_listen     = "0.0.0.0:26656"
# Local RPC endpoint (OpenAI-compat, gRPC; Phase 0 ships minimal JSON).
rpc_listen     = "127.0.0.1:8080"
# Prometheus `/metrics` endpoint. Keep bound to localhost by default.
metrics_listen = "127.0.0.1:9090"
bootstrap_peers = []
max_inbound_peers  = 60
max_outbound_peers = 20

# ─── Telemetry ─────────────────────────────────────────────────────────
[telemetry]
# Phase 0 always serves /metrics when the node is up; this flag controls
# whether the server binds at all (Phase 1 will gate it).
prometheus_enabled = true
# otlp_endpoint = "http://localhost:4317"
# sentry_dsn    = "https://..."
"#,
        data_dir = data_dir_literal,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use arknet_common::config::NodeConfig;

    #[tokio::test]
    async fn init_creates_layout_and_toml() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs { force: false }, Some(tmp.path()))
            .await
            .unwrap();

        assert!(paths::node_toml(tmp.path()).exists());
        assert!(paths::models_dir(tmp.path()).exists());
        assert!(paths::keys_dir(tmp.path()).exists());
        assert!(paths::logs_dir(tmp.path()).exists());
    }

    #[tokio::test]
    async fn init_refuses_overwrite_without_force() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs { force: false }, Some(tmp.path()))
            .await
            .unwrap();
        let err = run(InitArgs { force: false }, Some(tmp.path()))
            .await
            .unwrap_err();
        assert!(matches!(err, NodeError::Config(_)));
    }

    #[tokio::test]
    async fn init_overwrites_with_force() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs { force: false }, Some(tmp.path()))
            .await
            .unwrap();
        run(InitArgs { force: true }, Some(tmp.path()))
            .await
            .unwrap();
    }

    #[tokio::test]
    async fn generated_toml_is_loadable() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs { force: false }, Some(tmp.path()))
            .await
            .unwrap();

        // The generated file should round-trip through the shared loader
        // without errors — this catches comment / default-value drift
        // between the template and `NodeConfig` schema.
        let cfg = NodeConfig::load(paths::node_toml(tmp.path())).expect("config loads");
        assert_eq!(cfg.node.network, "devnet");
        assert!(cfg.roles.compute);
        assert!(cfg.telemetry.prometheus_enabled);
    }
}
